### ISSUE TITLE
Importing data

### ISSUE THREAD

**Issue by lucasmz-dev** [mjaakko/NeoStumbler#110]
The export feature is a bit confusing to me, you can export data but there's no way apparently to import it somewhere? Can one send these files to a location service? How does this work if I want to use it as a backup feature?

**Comment by mjaakko** [comment]
Right now I'm not aware of any services that would accept the exported data as input as-is. The main use case for exports is to be able to play around with the raw data, e.g. if you want to display the observations on a map. The export data format is just simple CSV files, so you can relatively easily tranform it to a another format if you want to send data to some location service.

There is no way to import the exported data back into NeoStumbler. It's intended that once you have sent the collected data to a location service, it can be removed from NeoStumbler
