### ISSUE TITLE
Add ability to delete reports

### ISSUE THREAD

**Issue by Coehill** [mjaakko/NeoStumbler#114]
This feature could be used if you made a reports that you don't want to upload and instead want to delete. I.e. if you were testing out the app or the area you recorded already has reports.

**Comment by mjaakko** [comment]
Good idea, I can see use for this! Would it be better to delete reports one by one or to have some kind of mass delete, e.g. by time range or area?

**Comment by Coehill** [comment]
> Good idea, I can see use for this! Would it be better to delete reports one by one or to have some kind of mass delete, e.g. by time range or area?

I only have a use for a deletion one-by-one but I can't speak to others' uses. Since it'll be simpler to have a delete button for each report, that, could be implemented first. Then an enhancement could be a mass-delete by time range or area, depending on peoples' needs.

**Comment by mjaakko** [comment]
This could be done with #101 - that would also allow the user to see what gets deleted with the report

**Comment by HorayNarea** [comment]
> Good idea, I can see use for this! Would it be better to delete reports one by one or to have some kind of mass delete, e.g. by time range or area?

I would prefer a range picker, similar to data export/reupload, but I date _and_ time range would be needed, not just date like it is in export/reupload currently

Maybe adding a time range selection to export would also be beneficial, I had a usecase¹ 3 years ago (and every now and then nowadays too) where this would have really helped. :thinking: 

¹ was trying to collect the mac addresses of free wifi in subway stations, if NeoStumbler with time range export would have existed back then I could just export the times when I was at a certain station afterwards
