### ISSUE TITLE
Full vs F-Droid and app updates

### ISSUE THREAD

**Issue by holdit** [mjaakko/NeoStumbler#135]
I think it would be useful for new users if readme.md listed the differences between the Full and F-Droid variants and clarified something about app updates. I just landed here after checking BeaconDB and have two questions:

I understand that the F-Droid variant doesn't include the Play Service bits, but in practice that means what? I noticed that it doesn't have the "fused location" option, is that it? Or is it missing something else that is nice to have?

Regarding updates, the F-Droid variant can be updated via the F-Droid and IzzyOnDroid repos. No info about the full version though. Do we have to manually check the releases page, does the app check for updates itself and notifies users, etc?

So essentially it would be nice if the readme had more information about this for newbies like me checking the app for the first time.

Thanks for your work!

**Comment by mjaakko** [comment]
> but in practice that means what? I noticed that it doesn't have the "fused location" option, is that it? Or is it missing something else that is nice to have?

The features missing from the fdroid variant are usage of fused location provider (https://developers.google.com/location-context/fused-location-provider) and automatic scanning, i.e. the scanner service can be started automatically when the device is moving (this uses Activity Recognition API from Google Play Services)

> Do we have to manually check the releases page, does the app check for updates itself and notifies users, etc?

Right now, you have to manually check for updates in GitHub. I'm thinking of adding support for semi-automated updates in the future, e.g. the app could download a new version of itself and prompt the user to install it -> #13 

I'll add these clarifications to the README!

**Comment by Mikaela** [comment]
You could also delegate update checking and automatic updates to Obtainium which downloads added apps from GitHub releases or similar sources. https://github.com/ImranR98/Obtainium/

**Comment by holdit** [comment]
@mjaakko Thanks, I understand the differences now.

Regarding updates, I'll probably use Obtainium as @Mikaela suggested. It could be useful to have an "about" page (or something in the settings section) with a link to this Github and some info about the version we are using (version number, full or f-droid).
