### ISSUE TITLE
Location button contrast

### ISSUE THREAD

**Issue by holdit** [mjaakko/NeoStumbler#137]
Sometimes it's hard to see button that makes the map "focus" on our location:

![img](https://github.com/user-attachments/assets/ae437a9d-cbf8-458a-8eb5-44dd62c612d3)

It's worse when the device is using dark mode as this icon turns white and the map doesn't have a dark mode, but even with a black icon, it can still be hard to see depending on what's behind the icon.

Apps usually work around this by having having a background around the icon, perhaps the same could be done here. For example:

![icon 1](https://github.com/user-attachments/assets/1d5f31e9-22b4-46c0-b50f-f72bc6f637af)

![icon](https://github.com/user-attachments/assets/e7131919-a3ce-4cb5-bd3b-08a53f21536a)

**Comment by AtmosphericIgnition** [comment]
I agree, the button is so small and has such little contrast that it is basically invisible most of the time.
