### ISSUE TITLE
Allow for translation using Weblate

### ISSUE THREAD

**Issue by lucasmz-dev** [mjaakko/NeoStumbler#144]
https://hosted.weblate.org/hosting/ provides free hosting with Weblate for Libre software. I think NeoStumbler might apply here.

https://translate.codeberg.org also I guess? I'm not sure how they go over there

This'd bring more attention from other translators which may not be as connected with the project. So there is that tradeoff. But overall, it should help the project.

**Comment by mjaakko** [comment]
I'll investigate available options. It would be useful to be able to track the translation status and to have an easier way to do translations without having to fork the repo etc.

**Comment by lucasmz-dev** [comment]
There's quite a few benefits too:

* You can change source strings without causing issues, translators see the current source, current un-used translation, and what has changed (you'd need to remove them in the other files if you changed anything, otherwise confusion will follow)
* Translators can set up email notifications for new strings, modified strings, etc (it's actually the default on Weblate IIRC)
* Built-in browser spell check helps
* Usable on phones

One downside is that you get merge conflicts with users that open PRs, so you shouldn't really merge those unless it's all just new files.

**Comment by mjaakko** [comment]
I've created a Weblate project for NeoStumbler: https://hosted.weblate.org/projects/neostumbler/

Not sure if I configured it correctly, but feel free to try it out. I'll request approval for libre hosting from Weblate

**Comment by lucasmz-dev** [comment]
HAH THIS IS FUNNY WE DID IT AT THE SAME TIME NO WAY

**Comment by lucasmz-dev** [comment]
Seems everything is pretty much fine, if anything I'll let you know
Did you set up Weblate to automatically pull? It's nice to have notifications right away

**Comment by mjaakko** [comment]
> Did you set up Weblate to automatically pull?

I added that to GitHub repo configuration, should be working
