### ISSUE TITLE
Keeping user location focused on the map view

### ISSUE THREAD

**Issue by AtmosphericIgnition** [mjaakko/NeoStumbler#146]
Currently, the button to focus on the current user location only snaps the map view onto the current user location, but does not keep the location focused as the user moves. Would you consider adding a toggle which would optionally keep the user location focused on the map screen as the user moves?

**Comment by mjaakko** [comment]
I'm planning on doing something like this, e.g. pressing the location button would keep the map centered on your location until the map view is moved manually

**Comment by AtmosphericIgnition** [comment]
Currently, the map zoom also resets to default the moment the user switches to a different tab.
