### ISSUE TITLE
Simplify persistent notification

### ISSUE THREAD

**Issue by nogweii** [mjaakko/NeoStumbler#151]
I don't mind the persistent notification, but the constantly updating values (number of reports and runtime) are ever so slightly distracting. Simplifying it to just say it's running would be appreciated.

**Comment by mjaakko** [comment]
This would have to be configurable by the user, others might want to see more details in the notification. Would it be good if you just disable notifications for the scanning service? E.g. "Scanning status" here:
![Screenshot_20240720_181400_Settings](https://github.com/user-attachments/assets/be03327c-1002-45d3-a4bf-8bc576745607)

**Comment by nogweii** [comment]
I like the reminder that it is running, so I don't want to disable the notification entirely.

Would you accept a PR with the change & setting?

**Comment by mjaakko** [comment]
> Would you accept a PR with the change & setting?

Sure, go ahead

**Comment by mjaakko** [comment]
I'm going to add more details to the notification. With that I could add an option to the settings to choose the amount of details to show in the notification
