### ISSUE TITLE
Store MCC and MNC as strings

### ISSUE THREAD

**Issue by mjaakko** [mjaakko/NeoStumbler#152]
Currently MCC and MNC are stored as an integer, which is incorrect as e.g. MNC "01" and "001" are separate networks (see https://en.wikipedia.org/wiki/Mobile_country_code)

Change this so that MCC and MNC are stored as strings in the DB. When sending data to the Geosubmit endpoint, they need to be converted back to an integer to keep compatibility with the Geosubmit specification

**Comment by joelkoen** [comment]
MNC 01 and 001 are both for testing - are there any other MCC/MNCs that need this?

Related: mozilla/ichnaea#1707

**Comment by mjaakko** [comment]
> MNC 01 and 001 are both for testing - are there any other MCC/MNCs that need this?

I'm not aware of any, so this is not a critical issue
