### ISSUE TITLE
Empty WiFi scans

### ISSUE THREAD

**Issue by AtmosphericIgnition** [mjaakko/NeoStumbler#167]
I have been seeing this behavior for a while now, but it seems like every 3 - 5th scan returns no WiFi networks, even as I remain in place in a dense urban area with WiFis all around me.

I tried resolving this by disabling WiFi Scan Throttling inside of developer options, but it seems to have no effect. See the screenshot below, I'm slowly walking through a dense residential area with apartment buildings, the same issue persists when I stand in place. I redacted the coordinates for privacy.

I'm using the latest GrapheneOS on a Pixel 8 Pro.
![signal-2024-07-24-220923](https://github.com/user-attachments/assets/c54bcb24-016b-4935-873d-5ca36f05b28b)

**Comment by AtmosphericIgnition** [comment]
I checked the application logs, but no events are logged.

**Comment by mjaakko** [comment]
This is expected as new reports are created every 20 seconds, but Wi-Fi scans are only done every 30 seconds due to scan throttling. In the next version you will be able to choose to ignore Wi-Fi scan throttling and in that case Wi-Fi scans will be done every 10 seconds

**Comment by mjaakko** [comment]
> Will it be possible to bring the scan frequency even lower, or is that the Android limit with WiFi scan throttling disabled?

Hmm, I'm not sure if that would improve the results, because it takes a while to detect the networks anyway. Will have to experiment to see how it works

**Comment by AtmosphericIgnition** [comment]
My idea would be a slider the user can adjust, with a sane default value.

Regarding the 10 seconds, I'm calculating what distance a person walks during 10 seconds. According to a random website, the average young person walks 1.36 m/s (4.9 km/h), this means that they will walk 13.6 meters between each scan. This is closer to 15 meters with my average walking speed. A bike going 12km/h will cover 33 meters, and a car going 30 km/h will cover 83 meters.

In case you prefer a fixed value, I would be willing to get in touch with the BeaconDB guy (or figure it out myself) and do some experiments to figure out what the optimal scan frequency might be.

**Comment by AtmosphericIgnition** [comment]
Fixed with 1.3.0
