### ISSUE TITLE
Missing numbers of contributed, sent and not sent reports in Android App Ver. 1.2.3

### ISSUE THREAD

**Issue by KreMic** [mjaakko/NeoStumbler#173]
### Description

Since Update to App Version 1.2.3 the number of reports being made, sent and not sent is not shown anymore. I contributed a lot till now without any issues and made a new scan to illustrate the behaviour in an attached screenshot.
I am currently on a Pixel 7 Pro with Android 14 and all applied patches. Till the update to version 1.2.3 everything worked fine. I use the version from F-Droid.

Sincere greetings from Vienna, KreMic

![Screenshot_20240725-170455~2](https://github.com/user-attachments/assets/779ab341-3e14-4a02-8e79-ef1c054f3fbc)

### App variant

F-Droid

### Version

1.2.3

### Device

Google Pixel 7 Pro

### Version

14

### New bug

- [X] I have checked that this bug has not been reported before

**Comment by mjaakko** [comment]
Might be caused by incorrect templates in the translation files. Could you check if it works when you change the language to English?

**Comment by KreMic** [comment]
Indeed it works if I switch to english, as you might have realized my locale is german.

**Comment by mjaakko** [comment]
Btw, there's a couple of translations missing for German locale. If you're interested, feel free to add translations for them and open a PR
