### ISSUE TITLE
Investigate uploading the app to F-Droid

### ISSUE THREAD

**Issue by mjaakko** [mjaakko/NeoStumbler#18]
Investigate what is needed to upload the application to F-Droid

* Create different build flavors to allow disabling / enabling features
  * This is needed to avoid including features which are dependent on proprietary libraries (i.e. Google Play services)
* Investigate replacing Google Play services with MicroG

**Comment by mjaakko** [comment]
NeoStumbler is now available from F-Droid: https://f-droid.org/packages/xyz.malkki.neostumbler.fdroid/

**Comment by IzzySoft** [comment]
@mjaakko and was available at IzzyOnDroid at that point as well: https://apt.izzysoft.de/packages/xyz.malkki.neostumbler.fdroid – and now I wonder if it shall be kept there, or if you prefer having it removed from there? Thanks to your having established reproducible builds, switching between the two is easily possible (should you e.g. need to push out some "emergency update" or F-Droid taking to long to build). If you want it kept, be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there :wink:

**Comment by IzzySoft** [comment]
@mjaakko while being here, on the recent release the IoD scanner reported:

```
! repo/xyz.malkki.neostumbler.fdroid_9.apk declares flag(s): usesCleartextTraffic
! repo/xyz.malkki.neostumbler.fdroid_9.apk declares sensitive permission(s): android.permission.ACCESS_BACKGROUND_LOCATION
! repo/xyz.malkki.neostumbler.fdroid_9.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

`ACCESS_BACKGROUND_LOCATION` is clear (I've just added it to the app's "green list"). But what is `usesCleartextTraffic` needed for? What server(s) are connected via unsecured (plain http) protocol?

As for `DEPENDENCY_INFO_BLOCK`, that can easily be avoided by a tiny modification of your `build.gradle`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

Thanks in advance!

**Comment by mjaakko** [comment]
@IzzySoft Yes, it's fine to have the app available there!
>But what is usesCleartextTraffic needed for? What server(s) are connected via unsecured (plain http) protocol?

By default, it's not used for anything. But the user can customize the endpoint where to send data and that might be using unencrypted HTTP

>As for DEPENDENCY_INFO_BLOCK, that can easily be avoided by a tiny modification of your build.gradle

I'll investigate this

**Comment by IzzySoft** [comment]
> Yes, it's fine to have the app available there!

Excellent! Marked it accordingly then.

> usesCleartextTraffic

Thanks! Added to the "green list" then:

```yaml
FlagIgnore:
  usesCleartextTraffic: not used by default but intended for use with endpoints in the local network, if specified
```

> `DEPENDENCY_INFO_BLOCK`

Thanks! If you think you need it for a potential PlayStore listing, you can leave it in for the AAB – IzzyOnDroid just pulls the APK (at least currently and in the foreseeable future).
