### ISSUE TITLE
Make BeaconDB the default for submissions

### ISSUE THREAD

**Issue by AtmosphericIgnition** [mjaakko/NeoStumbler#189]
### Description

All third party access to MLS has been [disabled](https://github.com/mozilla/ichnaea/issues/2065#issuecomment-2163573297) 2 months ago, and the service has not been accepting submissions for even longer than that.

Given that the developer of BeaconDB is actively working towards making data dumps available to ensure a situation like the loss of much of the MLS can't happen again, and the project has been floated as a potential replacement for MLS by a few important projects, I suggest switching the default submission endpoint to BeaconDB.

Even if you do not want to make BeaconDB the default, I do not think the default submission endpoint should be set to a retired service.

EDIT: Changed the GrapheneOS link for one with a more relevant statement from the project.

### Additional information

https://grapheneos.social/@GrapheneOS/112759471321669935

https://fosstodon.org/@mobian/112813739930744755

### New request

- [X] I have checked that a similar feature hasn't been requested yet

**Comment by lucasmz-dev** [comment]
> https://grapheneos.org/articles/positon-location-service

I would recommend against linking this, there's enough attacks as it is and there's not really much relevance into beacondb.net

**Comment by AtmosphericIgnition** [comment]
> > https://grapheneos.org/articles/positon-location-service
> 
> I would recommend against linking this, there's enough attacks as it is and there's not really much relevance into beacondb.net

Agreed. Replaced with a more relevant post from the project.

**Comment by lucasmz-dev** [comment]
Personally, I'm all for this! We can't cover the whole world alone. There's no other people really hosting endpoints that can be contributed to, as well as beacondb.net plan's to be to have an open db that anyone can use meaning other future location services can just plug in even if beaconDB was to die. 

Adding some info in the app store details could also be nice highlighting beaconDB instead of just "MLS compatible servers"

I'd mean people getting the app from F-Droid would already have a choice for them instead of having to look around, I find a lot of apps this way and this was originally how I found beacondb.net IIRC, but the app was unusable until then and still is

**Comment by joelkoen** [comment]
Alternative solution: https://github.com/mjaakko/NeoStumbler/issues/79#issuecomment-2238809609

**Comment by lucasmz-dev** [comment]
> Alternative solution: https://github.com/mjaakko/NeoStumbler/issues/79#issuecomment-2238809609

Listing available services would also be great, so having the code kind of prepared for that would be nice; I think for now just defaulting (and warning users that were on Mozilla's still) makes sense since there really doesn't seem to be anyone else hosting an API that allows submissions.

**Comment by AtmosphericIgnition** [comment]
I would also be for this solution. IMO, anything is better than having the default be submitting data to a dead service.

**Comment by mjaakko** [comment]
> Alternative solution: [#79 (comment)](https://github.com/mjaakko/NeoStumbler/issues/79#issuecomment-2238809609)

I think we'll go with this. This way users can easily discover available services and configure the endpoint, without making NeoStumbler tied to a single service. MLS could be kept as the default endpoint as an example – submissions there should just fail. 

Also, wording on the warning shown when first opening NeoStumbler could make it more clear that the default endpoint has to be changed and that there are suggestions for alternatives to MLS

**Comment by realpixelcode** [comment]
Instead of just a pure drop-down, it could feature check boxes in order to submit your data to several services at once.

**Comment by AtmosphericIgnition** [comment]
#124

**Comment by rimas-kudelis** [comment]
> I think we'll go with this. This way users can easily discover available services and configure the endpoint, without making NeoStumbler tied to a single service. MLS could be kept as the default endpoint as an example – submissions there should just fail.

Please reconsider. I just downloaded NeoStumbler and the first thing I had to do was go to its settings and choose the *only* service that it suggests instead of the default that is effectively dead.

I'm all for giving users a choice and keeping the UI as is, but a sane default should also be in place, especially when there's practically only one service that could be considered a sane default.

**Comment by rimas-kudelis** [comment]
> [@rimas-kudelis](https://github.com/rimas-kudelis) Yeah, it looks like BeaconDB has cemented its position as _the_ MLS replacement now that Geoclue and Linux distributions are starting to use it as the default, so I am planning on setting it as the default endpoint in also NeoStumbler. But because BeaconDB is still under development and [stores the raw submissions](https://codeberg.org/beacondb/beacondb/issues/12), there are some privacy concerns about setting it as the default. I've asked [@joelkoen](https://github.com/joelkoen) about this and once it's addressed, I'm ready to set BeaconDB as the default
> 
> I'm also thinking about alternative solutions for this, e.g. the dialog that shows up when opening NeoStumbler for the first time could ask whether to use BeaconDB as the default

@mjaakko, thanks for the explanation!  Both of your ideas seem fine to me.
The point of raw data collection is addressed in BeaconDB's privacy policy, so maybe I could argue that that should be enough? :)
