### ISSUE TITLE
Pre-release builds

### ISSUE THREAD

**Issue by mjaakko** [mjaakko/NeoStumbler#205]
To make it easier to test new features, add support for pre-release builds. These could be done with pre-release tags in GitHub, which would allow tools such as Obtainium to notify users about them

F-Droid metadata needs a filter for pre-release tags so that pre-release versions don't get published there:
https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/xyz.malkki.neostumbler.fdroid.yml

**Comment by HorayNarea** [comment]
But there are already APKs build for every commit, that anyone can download and try out?

For example https://github.com/mjaakko/NeoStumbler/actions/runs/10538761640 at the bottom of the page

![image](https://github.com/user-attachments/assets/73a0bac7-e30a-4027-bd15-adf5366dfe17)

**Comment by mjaakko** [comment]
> But there are already APKs build for every commit, that anyone can download and try out?

Yes, that's true. It's just not very user-friendly way to do it
