### ISSUE TITLE
Add air pressure to reports

### ISSUE THREAD

**Issue by mjaakko** [mjaakko/NeoStumbler#212]
Geosubmit v2 API supports including air pressure in the location data. This could be used by the server to estimate the altitude or to verify the altitude received from GPS

https://developer.android.com/develop/sensors-and-location/sensors/sensors_environment#sensors-using-temp

**Comment by joelkoen** [comment]
This could be incredibly helpful for verifying elevation values on the server: [beacondb#50](https://codeberg.org/beacondb/beacondb/issues/50).
