### ISSUE TITLE
Readme does not really explain advantage of full variant

### ISSUE THREAD

**Issue by rugk** [mjaakko/NeoStumbler#233]
It says about the F-Droid variant: 

> Features missing: fused location provider and automatic scanning

But hmm? As a user (non-Android-developer), I have no idea what "fused location (provider)" should mean?
About automated scanning I may have common sense, aka that it can run in the background or what(?), but again this may be the same?

As a new user not having used the app, this is somewhat unclear.

If I read further it says as a feature:
> Can be started automatically while moving (if using the full variant and Google Play Services are available)

Well... is this what is meant?

If so, I guess the Readme/docs could need some clarification here. 
After all, why not (also) just link to the Google docs on that topic?

**Comment by mjaakko** [comment]
Yeah, the README is written from a quite technical perspective atm. I'll see what I can do about it

To answer your questions:
* Fused location provider is this: https://developers.google.com/location-context/fused-location-provider
* Automatic scanning means that the scanning service can be started automatically when you're moving (this uses [Activity Recognition API](https://developers.google.com/location-context/activity-recognition) to do it in a battery-friendly way)

I guess there should also be better explanations for these inside the app. There are cases where you might want to not use the fused location provider, e.g. when contributing data to the same service you're using for network locations. This mainly applies to users of custom ROMs

**Comment by rugk** [comment]
Thanks a lot! Yeah, to improve support I've also made an issue for microG: https://github.com/microg/GmsCore/issues/2539
If implemented as a library one may also choose to bundle the feature and make it available in the F-Droid version, too.

**Comment by realeatham** [comment]
Wouldn't fused location lead to a feedback loop?

**Comment by mjaakko** [comment]
> Wouldn't fused location lead to a feedback loop?

Maybe, but only if you're contributing data to the same service you're using for network locations. But even then, it shouldn't be a problem and actually be useful in some cases, e.g. when mapping networks indoors

**Comment by mjaakko** [comment]
Anyway, the README should be slightly better now, so closing this issue
