### ISSUE TITLE
Clarify status of Mozilla Location Services (MLS)

### ISSUE THREAD

**Issue by rugk** [mjaakko/NeoStumbler#234]
The about description says:
> New stumbler application for contributing data to Mozilla Location Services 

The Readme is also mere reluctant:
> NeoStumbler is an Android application for collecting locations of cell towers, Wi-Fi access points and Bluetooth beacons to geolocation services, which have an API compatible with [Ichnaea](https://ichnaea.readthedocs.io/en/latest/api/geosubmit2.html) (i.e. Mozilla Location Services).

Hmm, so compatible ones?

## Background

AFAIK MLS is shut-down. https://github.com/mozilla/ichnaea/issues/2065

So as a user, I wonder what the alternatives are? This app may provide some?
But it's quite reluctant, is not it? Is there even a pre-selection included? (The Readme does not clarify that?)

The app would be a good point where this can be clarified…
Atwer all contributing only makes sense to a kind of central database.

**Comment by mjaakko** [comment]
In the next release, there will be a list of suggested alternatives for MLS. Currently this includes beacondb.net

I've also updated wording on the warning dialog, which is shown when opening NeoStumbler for the first time, to clarify that MLS has shut down and to prompt the user to change the endpoint

**Comment by mjaakko** [comment]
Closing this issue because the latest release should address this
