### ISSUE TITLE
Dutch translations contains UTF-8 for some reason invalidly rendered

### ISSUE THREAD

**Issue by skinkie** [mjaakko/NeoStumbler#366]
### Description

The MLS message. Writes "ook worden geëxporteerd als een ZIP-bestand" it is missing the "ë".

### App variant

full

### Version

1.4.2

### Device

Honor 200 Lite

### Android version

14

### New bug

- [X] I have checked that this bug has not been reported before

**Comment by mjaakko** [comment]
Looks like the letter ë is missing from the translation. Is it present in Weblate?

**Comment by skinkie** [comment]
Indeed was already wrong there.
