### ISSUE TITLE
statistics tab: does the tab count measurements or unique cells/SSIDs?

### ISSUE THREAD

**Issue by Djfe** [mjaakko/NeoStumbler#378]
### Description

the Statistics tab doesn't tell the user whether it counts unique Wi-Fi APs/Cells/Bluetooth Beacons or each measurement it did (including duplicates of the same Wi-Fi over and over again)

### Suggested implementation

This could be adjusted with an overhaul of the Statistics tab at some point.
It doesn't have to be fixed now, I just wanted to let you know that this is unclear to me as a user :)

### New request

- [X] I have checked that a similar feature hasn't been requested yet

**Comment by mjaakko** [comment]
It shows the number of unique APs/cell towers/beacons detected over time

This could be clarified at least in the user guide which I'm planning on creating

**Comment by Djfe** [comment]
great, in that case: closed
