### ISSUE TITLE
Publish F-droid variant to GitHub Releases

### ISSUE THREAD

**Issue by mjaakko** [mjaakko/NeoStumbler#64]
Update GitHub Actions pipelines to automatically upload .apk of the fdroid flavor when publishing new releases. This is needed for F-Droid reproducible builds

**Comment by devSJR** [comment]
Thanks for your efforts. As far as I know, Mozilla will keep accepting data but they will not process it. There is a lengthy discussion about future developments of MLS. It might be a good idea to inform users about these developments if you haven't done already.

Retiring the Mozilla Location Service #2065 

https://github.com/mozilla/ichnaea/issues/2065

**Comment by mjaakko** [comment]
> Thanks for your efforts. As far as I know, Mozilla will keep accepting data but they will not process it. There is a lengthy discussion about future developments of MLS. It might be a good idea to inform users about these developments if you haven't done already.
> 
> Retiring the Mozilla Location Service #2065
> 
> [mozilla/ichnaea#2065](https://github.com/mozilla/ichnaea/issues/2065)

I have created an issue about this, #66
