### ISSUE TITLE
Mozilla Location Services sunset announcement

### ISSUE THREAD

**Issue by Elinvention** [mjaakko/NeoStumbler#65]
Hi, I found this project thanks to f-droid and I immediately wondered wether MLS was going to stick around. According to https://github.com/mozilla/ichnaea/issues/2065 it doesn't look like it will.
So, I'm curios to know why this app now?

**Comment by mjaakko** [comment]
Yes, the release of this app happened with a little unfortunate timing, as I had just started the process of releasing this to F-Droid, when it was announced that MLS is going to shut down. The app has a feature for exporting the data as a .zip so there's still some use for it even though it can't upload data to MLS. I will add a warning to notify the users that uploading data to MLS is not possible anymore.

There is also an ongoing effort to create a replacement for MLS. If/when that is ready for use, I will add support for uploading data there

**Comment by RealTux678** [comment]
In addition to a possible MLS replacement, an additional option to add could be the possibility of being able to configure a shipment to a personalized MLS server. The user would enter the destination URL in the app settings.

**Comment by mjaakko** [comment]
> In addition to a possible MLS replacement, an additional option to add could be the possibility of being able to configure a shipment to a personalized MLS server. The user would enter the destination URL in the app settings.

There's an issue about this, #33. I'll do this for the next release, shouldn't take too long

**Comment by Coehill** [comment]
OpenCellID is still around for collecting cell towers.

**Comment by mjaakko** [comment]
Closing this issue because there is now an option to use a custom endpoint
