### ISSUE TITLE
Geosubmit with(out) API key?

### ISSUE THREAD

**Issue by HorayNarea** [mjaakko/NeoStumbler#71]
If I understand

https://github.com/mjaakko/NeoStumbler/blob/31648aa/app/src/main/java/xyz/malkki/neostumbler/geosubmit/MLSGeosubmit.kt#L18-L20

right, you currently don't use any API key for geosubmit.

Is that correct? Is there a way of setting an API key, other than hardcoding it in the URL in line 20?

**Comment by HorayNarea** [comment]
This may also be relevant for #33

**Comment by mjaakko** [comment]
Yes, that's correct. No API key is needed for anonymous data submissions to MLS (https://ichnaea.readthedocs.io/en/latest/api/geosubmit2.html)

For custom endpoints, I think there needs to be a way to set the API key. I'll update the description of #33 to include a note about API keys

**Comment by mjaakko** [comment]
Custom API keys can be used as of version 1.2.0
