### ISSUE TITLE
App crashes when trying to start scanning

### ISSUE THREAD

**Issue by AsmodeumX** [mjaakko/NeoStumbler#73]
I try to start scanning and then the app crashes immediately

**Comment by mjaakko** [comment]
Would you have more details available?

Which device and Android version are you using? Are you using fdroid or full variant of the application? Does this happen every time?

Also if you have any logs, that would be very useful

**Comment by AsmodeumX** [comment]
> Would you have more details available?
> 
> Which device and Android version are you using? Are you using fdroid or full variant of the application? Does this happen every time?
> 
> Also if you have any logs, that would be very useful

Samsung J8 Android 10
Downloaded from F-Droid 
Version 1.1.3

It happened every time I pressed "Start scanning"

**Comment by HorayNarea** [comment]
I have experienced the same crashing behaviour with a Redmi Note 9 Pro on Android 11 and the F-Droid Version, the Full Version works fine.

Haven't had time to investigate more but will try to do so tomorrow or the day after tomorrow.

**Comment by Jose92** [comment]
I encountered the same problem on Android 11, version F-Droid. 
In the file xyz.malkki.neostumbler.location.PlatformLocationSource I replaced :
`  locationManager.requestLocationUpdates(LocationManager.GPS_PROVIDER, locationIntervalMillis, 0.0f, locationListener)`
with 
`  locationManager.requestLocationUpdates(LocationManager.GPS_PROVIDER, locationIntervalMillis, 0.0f, locationListener, Looper.getMainLooper())`

(line 40)

and it works again.

**Comment by billie80** [comment]
I still experience crashes when trying to start a scan or accessing the map view with the F-Droid version. This doesn't happen with the Full version.

Device: Shift6mq, Android 10
NeoStumbler version: 1.2.3

Logs for both versions:
[f-droid.log](https://github.com/user-attachments/files/16215827/f-droid.log)
[full.log](https://github.com/user-attachments/files/16215828/full.log)

In the F-Droid log there is a permission violation error regarding location and then the App crashes.
However location and phone permission are granted

**Comment by mjaakko** [comment]
@billie80 Do you have GPS turned on? From the logs it looks like what might be happening is that GPS is turned off and that causes the crash because the callback function is not implemented

**Comment by billie80** [comment]
Ah, sorry you are correct. GPS was deactivated. It works if it is active.
Maybe this should be checked to avoid the crash.

**Comment by mjaakko** [comment]
> Ah, sorry you are correct. GPS was deactivated. It works if it is active. Maybe this should be checked to avoid the crash.

I've created a fix for this, #138
