### ISSUE TITLE
Failed to upload reports

### ISSUE THREAD

**Issue by jejo86** [mjaakko/NeoStumbler#80]
In the version downloaded from f-droid, I cannot send the reports.

Pressing the _Send reports_ button makes the button get grayed out for around a second, but the _Reports last uploaded field_ remains empty.

Selecting _Settings > Reupload data_ makes a _Failed to upload reports_ message appear.

**Comment by mjaakko** [comment]
Have you changed the endpoint where to send the data in the settings? MLS doesn't accept data submissions anymore and that's why it fails

For better UX I think there should be a message shown if uploading fails

**Comment by mjaakko** [comment]
Oh yeah, F-Droid doesn't have the latest version yet so you can't change the endpoint

**Comment by jejo86** [comment]
Ahh, too bad. My WiFi is still associated to a location I used to live at a few month ago. I keep getting located there, which is why I wanted to explicitly override the outdated data in MLS.

I hope MLS gets shut off soon, if no updated information can be pushed anymore.

**Comment by Komprogue** [comment]
> Have you changed the endpoint where to send the data in the settings? MLS doesn't accept data submissions anymore and that's why it fails
> 
> For better UX I think there should be a message shown if uploading fails

I've got a similar bug in the latest and previous releases: reports aren't being send to the beacondb, send button turns to gray for a couple of minutes, but after a while will be an error "Failed to upload reports".
And BTW, export data from settings results in creation of empty zip archive. 

![NS](https://github.com/user-attachments/assets/bd9d9cf2-b931-447d-9f06-89c363c36d08)
