### ISSUE TITLE
Btn scan - Text update

### ISSUE THREAD

**Issue by Jose92** [mjaakko/NeoStumbler#87]
I noticed that the scan start button did not change its text ( start / stop ) .

The notification is visible.

If you change fragment and go back to reports, the button text changes.

I've made a video to explain.

https://github.com/mjaakko/NeoStumbler/assets/5812028/ea89380d-5276-4be5-b177-efd3fc8ff366

**Comment by mjaakko** [comment]
Thanks for the bug report. Does this happen every time for you? I can reproduce this, but this only happens occasionally
