### ISSUE TITLE
Invalid WCDMA reports

### ISSUE THREAD

**Issue by joelkoen** [mjaakko/NeoStumbler#88]
When multiple WCDMA towers are recorded in the same report, only the first tower is valid:

```json
[
  {
    "age": 9215,
    "asu": 96,
    "cellId": 177013648,
    "locationAreaCode": 37265,
    "mobileCountryCode": 505,
    "mobileNetworkCode": 2,
    "primaryScramblingCode": 194,
    "radioType": "wcdma",
    "serving": 0,
    "signalStrength": -24
  },
  {
    "age": 9215,
    "asu": 96,
    "cellId": 23,
    "mobileCountryCode": 0,
    "mobileNetworkCode": 0,
    "primaryScramblingCode": 231,
    "radioType": "wcdma",
    "serving": 0,
    "signalStrength": -24
  },
  ...
]
```

- locationAreaCode is missing
- network and country codes are set to 0

I've noticed that my phone only seems to find exactly 1 or 32 wcdma cell towers. This does not occur when only 1 cell tower is recorded.

![Screenshot_20240527-175844_NeoStumbler](https://github.com/mjaakko/NeoStumbler/assets/122502655/6df29317-94f5-4811-98f9-316be20a06ed)

**Comment by joelkoen** [comment]
I'm able to reproduce this at home by forcing my phone to use 3G in settings.

**Comment by mjaakko** [comment]
Cell tower data depends a lot on your device and operating system. It seems that many devices only give the full set of values for the first cell tower

Unfortunately there's not much that can be done about this. Cell towers without useful data (i.e. at least MCC, MNC and cell ID) could be filtered out. We could also use data from the first cell tower to fill the missing values in other cell towers, if we can assume that all cell towers in the report belong to the same network

**Comment by joelkoen** [comment]
Now I've managed to get a WCDMA tower without a cell id, without any other cell towers to fill missing values from:

```json
  "cellTowers": [
    {
      "age": 6452,
      "asu": 96,
      "locationAreaCode": 37265,
      "mobileCountryCode": 505,
      "mobileNetworkCode": 2,
      "primaryScramblingCode": 223,
      "radioType": "wcdma",
      "serving": 0,
      "signalStrength": -24
    }
  ],
```

I'm pretty confident that this was observed when I made a call.

Given that this is more of a device/OS and data cleaning issue, I think I'll close this.
