### ISSUE TITLE
Ability to set the full path to endpoint

### ISSUE THREAD

**Issue by RealTux678** [mjaakko/NeoStumbler#89]
When using a custom endpoint, the app appends "/v2/geosubmit" to the address entered in the settings, which imposes rigid constraints on the server configuration.

**Comment by mjaakko** [comment]
Makes sense. I'll think about this and do it for the next release. Do you have any examples on how your API is configured?

**Comment by RealTux678** [comment]
For my server I have to add the .php extension after geosbumit for it to work. Ok, as for the subfolder, I can more easily rename it v2!

But yes, it would be comfort to have more margin regarding the configuration of the access path
