### ISSUE TITLE
Collect data for 5G cell towers

### ISSUE THREAD

**Issue by mjaakko** [mjaakko/NeoStumbler#90]
Currently no data is collected for 5G cell towers, because MLS does not support them. Add support for collecting data for 5G cell towers

Before implementation, investigate:
* How does Ichnaea handle fields with values it doesn't support?
  * If reports with 5G cell tower data are discarded, there needs to be a toggle in the settings whether to send the data
* How to map cell tower data (tracking area code etc.) to the data model?

**Comment by RealTux678** [comment]
Hi,
Regarding TAC or PCI, it is similar to LTE. Concerning the cellID, the important difference is that you must use a long type variable instead of integer.
OpenCellID has already implemented 5G. The radioType is "NR"

**Comment by HorayNarea** [comment]
> How does Ichnaea handle fields with values it doesn't support?
> 
>     * If reports with 5G cell tower data are discarded, there needs to be a toggle in the settings whether to send the data

I haven't tested it but as far as I can tell by looking at the code, fields that are not defined in Ichnaea's schemas are discarded _not entire reports_:

All `CellTower` classes which are used in the 3 different `Submit` endpoints inherit (through multiple others) from `StringVocabularyNode` in https://github.com/mozilla/ichnaea/blob/9e6529e/ichnaea/api/schema.py#L39-L54 which describes that:

> It removes the value if it isn't in the vocabulary.

And the vocabulary defined by all submit schemas is:

```py
RADIO_STRINGS = ["gsm", "cdma", "umts", "wcdma", "lte"]
```

…so, if a report with mutiple `cellTowers` also includes one with `radioType: "NR"`, it _should_ through out just that `cellTower`, nothing else.

**Comment by mjaakko** [comment]
Looks like Android returns 5G cell tower data (CellInfoNr) only when 5G standalone networks are in use
